name: VillagerBazaar
version: 0.1
main: github.fakandere.villagerBazaar.VillagerBazaarPlugin
depend: [Vault]
api-version: 1.16
commands:
  bazaar:
    description: Manages Your Bazaars
    usage: |
      /bazaar BazaarCommand