name: VillagerBazaar
version: 0.1
main: github.fakandere.villagerBazaar.VillagerBazaarPlugin
depend: [Vault]
commands:
  bazaar:
    description: Clears your own or a player's inventory.
    usage: |
      /bazaar Command
api-version: 1.16